### ISSUE TITLE
您好，这个插件能加入自定义按钮吗

### ISSUE THREAD

**Issue by FreeRotate** [WindRunnerMax/CanvasEditor#5]
![image](https://github.com/user-attachments/assets/1123e1e8-80bd-4284-ae66-8c3d82cf5270)

**Comment by WindRunnerMax** [comment]
这个是我写的富文本 https://github.com/WindRunnerMax/DocEditor

**Comment by FreeRotate** [comment]
> 这个是我写的富文本 https://github.com/WindRunnerMax/DocEditor

我知道，我是前端小白，如果自定义这个浮窗，只能clone这个https://github.com/WindRunnerMax/DocEditor到本地再修改吗？但目前这个doc-editor-core、delta、plugin版本是1.1.1的，我重新pnpm install后运行不起来，[https://github.com/WindRunnerMax/CanvasEditor/blob/master/packages/react/src/components/right-panel/components/text/index.tsx](url)报错不兼容，大佬能教一下怎么做吗

**Comment by WindRunnerMax** [comment]
这个版本引用的可能比较旧了，加自定义组件改这里的东西非常麻烦，因为你不仅要处理本身的富文本，还要处理 Canvas 来绘制富文本的新东西。

相当于一份菜做两份，很麻烦的，不建议搞

**Comment by FreeRotate** [comment]
> 这个版本引用的可能比较旧了，加自定义组件改这里的东西非常麻烦，因为你不仅要处理本身的富文本，还要处理 Canvas 来绘制富文本的新东西。相当于一份菜做两份，很麻烦的，不建议搞。

好的，感谢回复

**Comment by WindRunnerMax** [comment]
客气，你这是有什么需求吗。对于没有真正对应场景我不建议用 Canvas 来画，还是用 DOM 做起来方便，毕竟纯从图形上来处理这些东西总不如浏览器帮我们做了简单。

**Comment by WindRunnerMax** [comment]
DOM 的处理可以参考下 https://windrunnermax.github.io/ResumeEditor/

**Comment by FreeRotate** [comment]
> 客气，你这是有什么需求吗。对于没有真正对应场景我不建议用 Canvas 来画，还是用 DOM 做起来方便，毕竟纯从图形上来处理这些东西总不如浏览器帮我们做了简单。

我想加一个按钮，一键AI调整简历内容，就想在那个选中浮窗上加个按钮，把选中内容送到我的后台API里。我自己尝试改，只能在“富文本”那几个字边上加个按钮出来，但是这样很突兀
![image](https://github.com/user-attachments/assets/17fb2944-3178-4745-8a59-0a4653aa25f2)

**Comment by WindRunnerMax** [comment]
最近将编辑器换成了 https://github.com/WindRunnerMax/BlockKit，现在就非常容易自定义浮动工具栏了

https://github.com/WindRunnerMax/CanvasEditor/blob/9f9ff104924a0c57b624cd4f1e981c26597615dc/packages/react/src/components/right-panel/components/text/modules/editor.tsx#L130
